export default [
  {

    question_id: 1,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "The playground can be accessed safely by a sidewalk that is free of standing water, sand, pea gravel and low hanging branches.",
    reference: "",
    anstype: "noyesna",
    answerId: 1,
    response: "Yes",
    comments: "test comment",
    media: 0,
  },
  {

    question_id: 3,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "If needed, a suitable barrier(fence) is provided for border concerns within 100' of playground edge.  See question 3 for list of possible concerns",
    reference: "CPSC 6.1",
    anstype: "noyesna",
    answerId: null,
    response: null,
    comments: null,
    media: 0,
  },
  {

    question_id: 5,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "Seating (benches, outdoor tables, etc.) is in good condition (free of splinters, missing hardware or slats, protruding bolts, etc.)",
    reference: "",
    anstype: "noyesna",
    answerId: null,
    response: null,
    comments: null,
    media: 0,
  },
  {

    question_id: 7,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "Signs give information about: Regulations on the use of the playground (hours, pets, specific rules, etc.). Name and phone number of playground owner (to report problems). Age appropriateness of equipment",
    reference: "CPSC 6.3",
    anstype: "noyesna",
    answerId: null,
    response: null,
    comments: null,
    media: 0,
  },
  {

    question_id: 9,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "Signs on all bordering roads advise motorists that a playground is nearby.",
    reference: "",
    anstype: "noyesna",
    answerId: null,
    response: null,
    comments: null,
    media: 0,
  },
  {

    question_id: 11,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "Trash receptacles are provided and located outside of the play area.",
    reference: "",
    anstype: "noyesna",
    answerId: null,
    response: null,
    comments: null,
    media: 0,
  },
  {

    question_id: 13,
    category_id: 1,
    inspection_id: 1,
    short_display: "General",
    long_display: "General",
    req: 1,
    display: "Poisonous plants are removed from play area.",
    reference: "",
    anstype: "noyesna",
    answerId: null,
    response: null,
    comments: null,
    media: 0,
  },
]
;